const { defineConfig } = require('eslint/config')
const base = require('@infinitetoken/eslint-config/expo')

module.exports = defineConfig([
  ...base,
  // src/data/puzzleCatalog.generated.ts is auto-generated by hangman-scrapers/scripts/buildPuzzleCatalog.ts
  // and copied in as-is ("Do not edit manually") — not something to lint/format like hand-written source.
  {
    ignores: ['**/*.generated.ts']
  }
])
