/* eslint-disable @typescript-eslint/no-var-requires */
/* AUTO-GENERATED by scripts/buildPuzzleCatalog.ts. Do not edit manually. */

import type { Puzzle, PuzzleSource } from '../types/puzzle'

export type PuzzleManifestItem = {
  key: string
  file: string
  label: string
  count: number
  difficultyTiers: Array<'easy' | 'medium' | 'hard'>
  sources: PuzzleSource[]
  categories: string[]
}

export const puzzleManifest: PuzzleManifestItem[] = [
  {
    "key": "bands",
    "file": "bands.json",
    "label": "Bands",
    "count": 999,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "music-band"
    ],
    "categories": [
      "1980s Band",
      "2000s Band",
      "70s Band",
      "80s Band",
      "Actor Band",
      "Adult alternative pop/rock Band",
      "Alternative rock Band",
      "American Band",
      "American idol Band",
      "Anime Band",
      "Ballad Band",
      "Bluegrass Band",
      "Blues Band",
      "Blues rock Band",
      "Boogie rock Band",
      "British Band",
      "Britpop Band",
      "Canadian Band",
      "Christian rock Band",
      "Classic pop and rock Band",
      "Classic rock Band",
      "Classical Band",
      "Contemporary folk Band",
      "Country Band",
      "Country rock Band",
      "Crossover prog Band",
      "Dance Band",
      "Death by breast cancer Band",
      "Downtempo Band",
      "Eclectic prog Band",
      "Electronic Band",
      "Electronic rock Band",
      "English Band",
      "Experimental Band",
      "Film soundtrack Band",
      "Finnish rock Band",
      "Folk Band",
      "Folk rock Band",
      "French Band",
      "Funk Band",
      "German Band",
      "Germany Band",
      "Girl group Band",
      "Glam rock Band",
      "Greek Band",
      "Guitarist Band",
      "Hard rock Band",
      "Heartland rock Band",
      "Heavy metal Band",
      "Indie pop Band",
      "Indie rock Band",
      "Industrial Band",
      "Industrial rock Band",
      "Instrumental rock Band",
      "Irish Band",
      "Italian Band",
      "J-rock Band",
      "Japanese Band",
      "Jazz Band",
      "Jazz and blues Band",
      "Jefferson airplane Band",
      "Latin ballad Band",
      "Metal Band",
      "Minimalism Band",
      "Mpb Band",
      "Neo-medieval folk Band",
      "New age Band",
      "New jack swing Band",
      "New wave Band",
      "Noise Band",
      "Polish Band",
      "Political Band",
      "Pop Band",
      "Pop rock Band",
      "Pop/rock Band",
      "Post-punk Band",
      "Post-rock Band",
      "Progressive metal Band",
      "Progressive rock Band",
      "Proto-punk Band",
      "Psychedelic pop Band",
      "Psychedelic rock Band",
      "Psychedelic soul Band",
      "Punk Band",
      "Punk rock Band",
      "R&b Band",
      "Rap Band",
      "Reggae Band",
      "Rock Band",
      "Rock and indie Band",
      "Rock and roll Band",
      "Rockabilly Band",
      "Russian Band",
      "Shoegaze Band",
      "Singer Band",
      "Singer-songwriter Band",
      "Ska Band",
      "Slowcore Band",
      "Soft rock Band",
      "Soul Band",
      "Soundtrack Band",
      "Southern rock Band",
      "Spanish Band",
      "Strings Band",
      "Swedish Band",
      "Symphonic metal Band",
      "Symphonic prog Band",
      "Synthpop Band",
      "Texas Band",
      "Traditional pop Band",
      "Trance Band",
      "Trip-hop Band"
    ]
  },
  {
    "key": "geographyCities",
    "file": "geographyCities.json",
    "label": "Geography Cities",
    "count": 83,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "geography"
    ],
    "categories": [
      "World City"
    ]
  },
  {
    "key": "geographyCountries",
    "file": "geographyCountries.json",
    "label": "Geography Countries",
    "count": 239,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "geography"
    ],
    "categories": [
      "Country"
    ]
  },
  {
    "key": "geographyLandmarksUNESCO",
    "file": "geographyLandmarksUNESCO.json",
    "label": "Geography Landmarks UNESCO",
    "count": 1255,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "geography"
    ],
    "categories": [
      "World Heritage Site"
    ]
  },
  {
    "key": "geographyNationalParks",
    "file": "geographyNationalParks.json",
    "label": "Geography National Parks",
    "count": 95,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "geography"
    ],
    "categories": [
      "National Park"
    ]
  },
  {
    "key": "geographyUSStates",
    "file": "geographyUSStates.json",
    "label": "Geography USStates",
    "count": 135,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "geography"
    ],
    "categories": [
      "US State",
      "US State Capital"
    ]
  },
  {
    "key": "geographyWorldWonders",
    "file": "geographyWorldWonders.json",
    "label": "Geography World Wonders",
    "count": 21,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "geography"
    ],
    "categories": [
      "World Wonder"
    ]
  },
  {
    "key": "movies",
    "file": "movies.json",
    "label": "Movies",
    "count": 200,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "movie"
    ],
    "categories": [
      "Action",
      "Comedy",
      "Drama",
      "Horror",
      "Movie",
      "Romance",
      "Sci-Fi"
    ]
  },
  {
    "key": "phrases",
    "file": "phrases.json",
    "label": "Phrases",
    "count": 507,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "phrases"
    ],
    "categories": [
      "food-and-drink",
      "people",
      "phrase",
      "place",
      "thing",
      "what-are-you-doing"
    ]
  },
  {
    "key": "songs",
    "file": "songs.json",
    "label": "Songs",
    "count": 1965,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "music-song"
    ],
    "categories": [
      "Song"
    ]
  },
  {
    "key": "themeActors",
    "file": "themeActors.json",
    "label": "Theme Actors",
    "count": 50,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Actor"
    ]
  },
  {
    "key": "themeBoardGamesToys",
    "file": "themeBoardGamesToys.json",
    "label": "Theme Board Games Toys",
    "count": 514,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Board Game or Toy"
    ]
  },
  {
    "key": "themeBrandsProducts",
    "file": "themeBrandsProducts.json",
    "label": "Theme Brands Products",
    "count": 485,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Brand"
    ]
  },
  {
    "key": "themeCartoons",
    "file": "themeCartoons.json",
    "label": "Theme Cartoons",
    "count": 68,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Cartoon Character"
    ]
  },
  {
    "key": "themeCompanies",
    "file": "themeCompanies.json",
    "label": "Theme Companies",
    "count": 49,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Company"
    ]
  },
  {
    "key": "themeFirstLadies",
    "file": "themeFirstLadies.json",
    "label": "Theme First Ladies",
    "count": 54,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "First Lady"
    ]
  },
  {
    "key": "themeFoodAndDrink",
    "file": "themeFoodAndDrink.json",
    "label": "Theme Food And Drink",
    "count": 459,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Food and Drink"
    ]
  },
  {
    "key": "themeHistory",
    "file": "themeHistory.json",
    "label": "Theme History",
    "count": 173,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "History"
    ]
  },
  {
    "key": "themeHolidaysCelebrations",
    "file": "themeHolidaysCelebrations.json",
    "label": "Theme Holidays Celebrations",
    "count": 32,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Holiday and Celebration"
    ]
  },
  {
    "key": "themeLiterature",
    "file": "themeLiterature.json",
    "label": "Theme Literature",
    "count": 304,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Book Title"
    ]
  },
  {
    "key": "themeMovieTitles",
    "file": "themeMovieTitles.json",
    "label": "Theme Movie Titles",
    "count": 123,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Movie Title"
    ]
  },
  {
    "key": "themeMusicByEra",
    "file": "themeMusicByEra.json",
    "label": "Theme Music By Era",
    "count": 68,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Music Artist by Era"
    ]
  },
  {
    "key": "themeMythology",
    "file": "themeMythology.json",
    "label": "Theme Mythology",
    "count": 753,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Mythology Figure"
    ]
  },
  {
    "key": "themeNature",
    "file": "themeNature.json",
    "label": "Theme Nature",
    "count": 1098,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Nature"
    ]
  },
  {
    "key": "themeProgrammingLanguages",
    "file": "themeProgrammingLanguages.json",
    "label": "Theme Programming Languages",
    "count": 611,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Programming Language"
    ]
  },
  {
    "key": "themeScienceSpace",
    "file": "themeScienceSpace.json",
    "label": "Theme Science Space",
    "count": 27,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Planet",
      "Space Mission"
    ]
  },
  {
    "key": "themeSportsTeams",
    "file": "themeSportsTeams.json",
    "label": "Theme Sports Teams",
    "count": 164,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Sports Team"
    ]
  },
  {
    "key": "themeSuperheroes",
    "file": "themeSuperheroes.json",
    "label": "Theme Superheroes",
    "count": 392,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Superhero"
    ]
  },
  {
    "key": "themeTechnology",
    "file": "themeTechnology.json",
    "label": "Theme Technology",
    "count": 136,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Technology"
    ]
  },
  {
    "key": "themeTravel",
    "file": "themeTravel.json",
    "label": "Theme Travel",
    "count": 50,
    "difficultyTiers": [
      "easy",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Travel"
    ]
  },
  {
    "key": "themeTVShows",
    "file": "themeTVShows.json",
    "label": "Theme TVShows",
    "count": 181,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "TV Show"
    ]
  },
  {
    "key": "themeUSPresidents",
    "file": "themeUSPresidents.json",
    "label": "Theme USPresidents",
    "count": 48,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "US President"
    ]
  },
  {
    "key": "themeVehicles",
    "file": "themeVehicles.json",
    "label": "Theme Vehicles",
    "count": 66,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Vehicle"
    ]
  },
  {
    "key": "themeVideoGames",
    "file": "themeVideoGames.json",
    "label": "Theme Video Games",
    "count": 971,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Video Game"
    ]
  },
  {
    "key": "themeWordplay",
    "file": "themeWordplay.json",
    "label": "Theme Wordplay",
    "count": 26,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "theme"
    ],
    "categories": [
      "Wordplay"
    ]
  },
  {
    "key": "trivia",
    "file": "trivia.json",
    "label": "Trivia",
    "count": 10000,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "trivia"
    ],
    "categories": [
      "\"A\" PLUS",
      "\"G\" WHIZ",
      "\"G\" WHIZ!",
      "\"J\" WALKING",
      "\"T\" TIME",
      "\"W\"ORDS",
      "-OLOGIES",
      "10-LETTER WORDS",
      "11-LETTER WORDS",
      "12-LETTER WORDS",
      "13-LETTER WORDS",
      "15-LETTER WORDS",
      "1984",
      "19th CENTURY AMERICA",
      "2-LETTER WORDS",
      "20th CENTURY AMERICA",
      "20th CENTURY NOVELS",
      "20th CENTURY WOMEN",
      "3-LETTER WORDS",
      "4-LETTER WORDS",
      "5-LETTER WORDS",
      "6-LETTER WORDS",
      "7-LETTER WORDS",
      "9-LETTER WORDS",
      "ABBREV.",
      "ABBREVIATIONS",
      "ACTORS & ACTRESSES",
      "ACTORS & ROLES",
      "ACTORS & THEIR ROLES",
      "ACTRESSES",
      "ADD A LETTER",
      "ADJECTIVES",
      "AFRICA",
      "AFRICAN AMERICANS",
      "AFRICAN HISTORY",
      "AGRICULTURE",
      "AIRPORT CODES",
      "ALBUMS",
      "ALPHABETICALLY LAST",
      "AMERICAN AUTHORS",
      "AMERICAN HISTORY",
      "AMERICAN HODGEPODGE",
      "AMERICAN INDIANS",
      "AMERICAN LIT",
      "AMERICAN LITERATURE",
      "AMERICANA",
      "ANAGRAMS",
      "ANATOMY",
      "ANCIENT HISTORY",
      "ANCIENT ROME",
      "ANCIENT TIMES",
      "ANIMALS",
      "ANNUAL EVENTS",
      "ANTONYMS",
      "ARCHAEOLOGY",
      "ARCHITECTS",
      "ARCHITECTURE",
      "AROUND THE HOUSE",
      "AROUND THE WORLD",
      "ART",
      "ART & ARTISTS",
      "ART HISTORY",
      "ARTISTS",
      "ARTISTS & THEIR SUBJECTS",
      "ARTS & CRAFTS",
      "ASIA",
      "ASTRONOMY",
      "AT THE MOVIES",
      "ATHLETES",
      "AUTHORS",
      "AUTHORS & THEIR WORKS",
      "AUTHORS' RHYME TIME",
      "AVIATION",
      "AWARDS",
      "AWARDS & HONORS",
      "BACKWORDS",
      "BALLET",
      "BASEBALL",
      "BEASTLY EXPRESSIONS",
      "BEASTLY RHYME TIME",
      "BEFORE & AFTER",
      "BESTSELLERS",
      "BETTER KNOWN AS...",
      "BIBLICAL QUOTES",
      "BIOGRAPHIES",
      "BIOLOGY",
      "BIRDS",
      "BLACK AMERICA",
      "BLACK AMERICANS",
      "BODIES OF WATER",
      "BODY LANGUAGE",
      "BOOK TITLES",
      "BOOKS & AUTHORS",
      "BORN & DIED",
      "BOTANY",
      "BRAND NAMES",
      "BRIDGES",
      "BRIT LIT",
      "BRITISH AUTHORS",
      "BRITISH HISTORY",
      "BRITISH ROYALTY",
      "BROADWAY",
      "BROADWAY LYRICS",
      "BROADWAY MUSICALS",
      "BUSINESS & INDUSTRY",
      "BY THE NUMBERS",
      "CAPITAL PUNISHMENT",
      "CATS & DOGS",
      "CELEBRITIES",
      "CELEBRITY BOOKS",
      "CELEBRITY RELATIVES",
      "CELEBRITY RHYME TIME",
      "CELEBS",
      "CHEMISTRY",
      "CHILDREN'S LIT",
      "CHILDREN'S LITERATURE",
      "CLASSICAL COMPOSERS",
      "CLASSICAL MUSIC",
      "CLIFFS NOTES",
      "COLLEGE FOOTBALL",
      "COLLEGES & UNIVERSITIES",
      "COLONIAL AMERICA",
      "COLOR MY WORLD",
      "COLORS",
      "COMMON BONDS",
      "COMMUNICATION",
      "COMPOSERS",
      "COMPOUND WORDS",
      "COOKING",
      "CORPORATE AMERICA",
      "COUNTRIES OF THE WORLD",
      "COUNTRY MUSIC",
      "CROSSWORD CLUES \"A\"",
      "CROSSWORD CLUES \"C\"",
      "CROSSWORD CLUES \"F\"",
      "CROSSWORD CLUES \"G\"",
      "CROSSWORD CLUES \"K\"",
      "CROSSWORD CLUES \"L\"",
      "CROSSWORD CLUES \"M\"",
      "CROSSWORD CLUES \"P\"",
      "CROSSWORD CLUES \"S\"",
      "CROSSWORD CLUES \"T\"",
      "DANCE",
      "DESIGN",
      "DOCUMENTARIES",
      "DOGS",
      "DOUBLE TALK",
      "DRAMA",
      "EARLY AMERICA",
      "ECONOMICS",
      "EDUCATION",
      "ENGINEERING",
      "ENGLISH LIT",
      "ENGLISH LITERATURE",
      "EPONYMS",
      "ETIQUETTE",
      "EUROPE",
      "EUROPEAN CITIES",
      "EUROPEAN GEOGRAPHY",
      "EUROPEAN HISTORY",
      "EXPLORATION",
      "EXPLORERS",
      "FACTS & FIGURES",
      "FAMILIAR PHRASES",
      "FAMOUS AMERICANS",
      "FAMOUS FIRSTS",
      "FAMOUS NAMES",
      "FAMOUS PAIRS",
      "FAMOUS QUOTES",
      "FAMOUS WOMEN",
      "FASHION",
      "FASHION DESIGNERS",
      "FASHION HISTORY",
      "FASHION STATEMENTS",
      "FICTION",
      "FICTIONAL CHARACTERS",
      "FILL IN THE BOOK TITLE",
      "FILMS OF THE '70s",
      "FILMS OF THE '90s",
      "FIRST LADIES",
      "FIRST NAME'S THE SAME",
      "FIRST NAMES",
      "FIRST NOVELS",
      "FIRST THINGS FIRST",
      "FISH",
      "FIX THE PROVERB",
      "FLAGS",
      "FLAGS OF THE WORLD",
      "FLOWERS",
      "FOOD",
      "FOOD & DRINK",
      "FOOD FACTS",
      "FOOTBALL",
      "FOR THE BIRDS",
      "FOREIGN WORDS & PHRASES",
      "FRENCH HISTORY",
      "FROM PAGE TO SCREEN",
      "FROM THE FRENCH",
      "FROM THE GREEK",
      "FROM THE LATIN",
      "FRUIT",
      "FRUITS & VEGETABLES",
      "FUN WITH OPERA",
      "FURNITURE",
      "GAMES",
      "GARDENING",
      "GEMS",
      "GEMS & JEWELRY",
      "GENERAL SCIENCE",
      "GENESIS",
      "GEOGRAPHY",
      "GEOLOGY",
      "GEOMETRY",
      "GET YOUR FACTS STRAIGHT",
      "GOLF",
      "GOULASH",
      "GOVERNMENT",
      "GOVERNMENT & POLITICS",
      "GOVERNORS",
      "GRAB BAG",
      "GRAMMAR",
      "GREEK MYTHOLOGY",
      "GUINNESS RECORDS",
      "HAIL TO THE CHIEF",
      "HALLS OF FAME",
      "HE WAS IN THAT?",
      "HEALTH & MEDICINE",
      "HERBS & SPICES",
      "HIGHWAYS & BYWAYS",
      "HINTS FROM HELOISE",
      "HISTORIC AMERICANS",
      "HISTORIC NAMES",
      "HISTORIC PEOPLE",
      "HISTORIC WOMEN",
      "HISTORICAL NOVELS",
      "HISTORY",
      "HODGEPODGE",
      "HOLIDAYS",
      "HOLIDAYS & OBSERVANCES",
      "HOMOPHONES",
      "IF THEY MARRIED...",
      "IN THE BOOKSTORE",
      "IN THE DICTIONARY",
      "IN THE NEWS",
      "INCREDIBLE EDIBLES",
      "INSECTS",
      "INTERNATIONAL CUISINE",
      "INTERNATIONAL FOOD & DRINK",
      "INVENTIONS",
      "INVENTIVE MINDS",
      "INVENTORS",
      "INVENTORS & INVENTIONS",
      "ISLANDS",
      "IT'S A GROUP THING",
      "JAPAN",
      "JUST DESSERTS",
      "KIDDY LIT",
      "LABOR",
      "LAKES & RIVERS",
      "LANDMARKS",
      "LANGUAGES",
      "LAST NAME'S THE SAME",
      "LAW",
      "LEFTOVERS",
      "LESSER-KNOWN NAMES",
      "LETTER PERFECT",
      "LIBRARIES",
      "LITERARY BEFORE & AFTER",
      "LITERARY CHARACTERS",
      "LITERARY HODGEPODGE",
      "LITERARY QUOTES",
      "LITERARY TERMS",
      "LITERATURE",
      "MAGAZINES",
      "MAMMALS",
      "MATH",
      "MATHEMATICS",
      "MEDICINE",
      "METALS",
      "MIDDLE NAMES",
      "MILITARY MATTERS",
      "MISSING LINKS",
      "MONEY",
      "MOUNTAINS",
      "MOVIE DEBUTS",
      "MOVIE DIRECTORS",
      "MOVIE MUSICALS",
      "MOVIE QUOTES",
      "MOVIE SONGS",
      "MOVIE TAGLINES",
      "MOVIE TRIVIA",
      "MOVIES",
      "MUSEUMS",
      "MUSIC",
      "MUSIC APPRECIATION",
      "MUSIC CLASS",
      "MUSICAL INSTRUMENTS",
      "MUSICAL THEATRE",
      "MUSICALS",
      "MYTHOLOGY",
      "MYTHS & LEGENDS",
      "NAME THE MOVIE",
      "NATIONAL ANTHEMS",
      "NATIONAL PARKS",
      "NATIVE AMERICANS",
      "NATURE",
      "NATURE STUDY",
      "NEWSPAPERS",
      "NEWSPAPERS & MAGAZINES",
      "NICKNAMES",
      "NONFICTION",
      "NOTABLE NAMES",
      "NOTABLE WOMEN",
      "NOTORIOUS",
      "NOVELS",
      "NUMBER, PLEASE",
      "NURSERY RHYMES",
      "NUTRITION",
      "OCCUPATIONS",
      "ODD WORDS",
      "ODDS & ENDS",
      "OFFICIAL STATE STUFF",
      "OFFICIAL STATE THINGS",
      "ON THE GO",
      "ON THE MAP",
      "OPERA",
      "ORGANIZATIONS",
      "PARTS OF THE WHOLE",
      "PEN NAMES",
      "PEOPLE",
      "PEOPLE & PLACES",
      "PEOPLE IN HISTORY",
      "PHILOSOPHY",
      "PHOTOGRAPHY",
      "PHYSICAL SCIENCE",
      "PHYSICS",
      "PLANTS",
      "PLANTS & TREES",
      "PLAYS",
      "PLAYS & PLAYWRIGHTS",
      "PLAYWRIGHTS",
      "POETRY",
      "POETS",
      "POETS & POETRY",
      "POLITICIANS",
      "POLITICS",
      "POP CULTURE",
      "POP MUSIC",
      "POT LUCK",
      "POTENT POTABLES",
      "POTPOURRI",
      "PRESIDENTIAL TRIVIA",
      "PRESIDENTS",
      "PRO FOOTBALL",
      "PROVERBS",
      "PSYCHOLOGY",
      "PUT 'EM IN ORDER",
      "QUASI-RELATED PAIRS",
      "QUOTATIONS",
      "QUOTES",
      "RANKS & TITLES",
      "RELIGION",
      "RELIGIOUS LEADERS",
      "RHYME TIME",
      "RIVERS",
      "ROCK",
      "ROCKS & MINERALS",
      "ROYALTY",
      "RULERS",
      "SAINTS",
      "SAME FIRST & LAST LETTER",
      "SCIENCE",
      "SCIENCE & NATURE",
      "SCIENCE & TECHNOLOGY",
      "SCIENCE CLASS",
      "SCIENCE GUYS",
      "SCIENTISTS",
      "SCULPTURE",
      "SHAKESPEARE",
      "SHAKESPEAREAN CHARACTERS",
      "SHIPS",
      "SHORT STORIES",
      "SIGNS & SYMBOLS",
      "SINGERS",
      "SLOGANEERING",
      "SOCIOLOGY",
      "SONG LYRICS",
      "SONGS",
      "SOUTH AMERICA",
      "SPORTS",
      "SPORTS LEGENDS",
      "SPORTS NICKNAMES",
      "SPORTS STARS",
      "STAR WARS",
      "STATE CAPITALS",
      "STATE FACTS",
      "STATE FLAGS",
      "STATE NICKNAMES",
      "STOCK SYMBOLS",
      "STUPID ANSWERS",
      "SUPERSTITIONS",
      "TECHNOLOGY",
      "TELEVISION",
      "THAT'S SO CLICHE!",
      "THE 1930s",
      "THE 1960s",
      "THE 1980s",
      "THE 19th CENTURY",
      "THE 20th CENTURY",
      "THE 50 STATES",
      "THE AMERICAN REVOLUTION",
      "THE ANIMAL KINGDOM",
      "THE BIBLE",
      "THE BODY HUMAN",
      "THE CABINET",
      "THE CINEMA",
      "THE CIVIL WAR",
      "THE DIRECTOR'S CHAIR",
      "THE ELEMENTS",
      "THE EMMYS",
      "THE ENVIRONMENT",
      "THE HISTORY CHANNEL",
      "THE HUMAN BODY",
      "THE LARGEST IN AREA",
      "THE LAW",
      "THE MIDDLE AGES",
      "THE MOVIES",
      "THE NEW TESTAMENT",
      "THE OLD TESTAMENT",
      "THE OLD WEST",
      "THE OLYMPICS",
      "THE OSCARS",
      "THE QUEEN'S ENGLISH",
      "THE SHORT FORM",
      "THE SILVER SCREEN",
      "THE SMALLEST IN AREA",
      "THE SOLAR SYSTEM",
      "THE SUPREME COURT",
      "THE U.S. CONSTITUTION",
      "THE UNITED NATIONS",
      "THEATER",
      "THEATRE",
      "THIS & THAT",
      "TIME",
      "TOYS & GAMES",
      "TRANSPORTATION",
      "TRAVEL & TOURISM",
      "TRAVEL EUROPE",
      "TRAVEL U.S.A.",
      "TREES",
      "TRIVIA",
      "TV",
      "TV ACTORS & ROLES",
      "TV CHARACTERS",
      "TV TRIVIA",
      "U.S. CITIES",
      "U.S. COINS",
      "U.S. GEOGRAPHY",
      "U.S. GOVERNMENT",
      "U.S. HISTORY",
      "U.S. PRESIDENTS",
      "U.S. STAMPS",
      "U.S. STATES",
      "U.S.A.",
      "UNREAL ESTATE",
      "VERBS",
      "VICE PRESIDENTS",
      "VOCABULARY",
      "WEAPONS",
      "WEATHER",
      "WEBSITES",
      "WEIGHTS & MEASURES",
      "WHAT'S IN A NAME?",
      "WHERE AM I?",
      "WHICH CAME FIRST?",
      "WHO PLAYED 'EM?",
      "WINE",
      "WOMEN",
      "WOMEN AUTHORS",
      "WOMEN IN HISTORY",
      "WOMEN IN SPORTS",
      "WOMEN WRITERS",
      "WOMEN'S FIRSTS",
      "WORD & PHRASE ORIGINS",
      "WORD ORIGINS",
      "WORD PUZZLES",
      "WORDS",
      "WORLD CAPITALS",
      "WORLD CITIES",
      "WORLD FACTS",
      "WORLD GEOGRAPHY",
      "WORLD HISTORY",
      "WORLD LEADERS",
      "WORLD LITERATURE",
      "WORLD RELIGION",
      "WORLD TRAVEL",
      "WORLD WAR I",
      "WORLD WAR II",
      "YOU DO THE MATH",
      "ZOOLOGY"
    ]
  },
  {
    "key": "tvShows",
    "file": "tvShows.json",
    "label": "Tv Shows",
    "count": 200,
    "difficultyTiers": [
      "easy",
      "hard",
      "medium"
    ],
    "sources": [
      "tv"
    ],
    "categories": [
      "Comedy",
      "Drama",
      "TV Show"
    ]
  }
]

const loaders: Record<string, () => Puzzle[]> = {
  'bands': () => {
    const mod = require('../../data/bands.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'geographyCities': () => {
    const mod = require('../../data/geographyCities.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'geographyCountries': () => {
    const mod = require('../../data/geographyCountries.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'geographyLandmarksUNESCO': () => {
    const mod = require('../../data/geographyLandmarksUNESCO.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'geographyNationalParks': () => {
    const mod = require('../../data/geographyNationalParks.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'geographyUSStates': () => {
    const mod = require('../../data/geographyUSStates.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'geographyWorldWonders': () => {
    const mod = require('../../data/geographyWorldWonders.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'movies': () => {
    const mod = require('../../data/movies.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'phrases': () => {
    const mod = require('../../data/phrases.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'songs': () => {
    const mod = require('../../data/songs.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeActors': () => {
    const mod = require('../../data/themeActors.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeBoardGamesToys': () => {
    const mod = require('../../data/themeBoardGamesToys.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeBrandsProducts': () => {
    const mod = require('../../data/themeBrandsProducts.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeCartoons': () => {
    const mod = require('../../data/themeCartoons.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeCompanies': () => {
    const mod = require('../../data/themeCompanies.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeFirstLadies': () => {
    const mod = require('../../data/themeFirstLadies.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeFoodAndDrink': () => {
    const mod = require('../../data/themeFoodAndDrink.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeHistory': () => {
    const mod = require('../../data/themeHistory.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeHolidaysCelebrations': () => {
    const mod = require('../../data/themeHolidaysCelebrations.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeLiterature': () => {
    const mod = require('../../data/themeLiterature.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeMovieTitles': () => {
    const mod = require('../../data/themeMovieTitles.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeMusicByEra': () => {
    const mod = require('../../data/themeMusicByEra.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeMythology': () => {
    const mod = require('../../data/themeMythology.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeNature': () => {
    const mod = require('../../data/themeNature.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeProgrammingLanguages': () => {
    const mod = require('../../data/themeProgrammingLanguages.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeScienceSpace': () => {
    const mod = require('../../data/themeScienceSpace.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeSportsTeams': () => {
    const mod = require('../../data/themeSportsTeams.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeSuperheroes': () => {
    const mod = require('../../data/themeSuperheroes.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeTechnology': () => {
    const mod = require('../../data/themeTechnology.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeTravel': () => {
    const mod = require('../../data/themeTravel.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeTVShows': () => {
    const mod = require('../../data/themeTVShows.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeUSPresidents': () => {
    const mod = require('../../data/themeUSPresidents.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeVehicles': () => {
    const mod = require('../../data/themeVehicles.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeVideoGames': () => {
    const mod = require('../../data/themeVideoGames.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'themeWordplay': () => {
    const mod = require('../../data/themeWordplay.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'trivia': () => {
    const mod = require('../../data/trivia.json')
    return (mod?.default ?? mod) as Puzzle[]
  },
  'tvShows': () => {
    const mod = require('../../data/tvShows.json')
    return (mod?.default ?? mod) as Puzzle[]
  }
}

export const loadPuzzlesByKey = (key: string): Puzzle[] => {
  const loader = loaders[key]
  if (!loader) return []
  return loader()
}

export const loadAllPuzzles = (): Puzzle[] => {
  const combined = new Map<string, Puzzle>()

  for (const item of puzzleManifest) {
    const puzzles = loadPuzzlesByKey(item.key)
    for (const puzzle of puzzles) {
      const k = `${puzzle.id}:${puzzle.category}`
      if (!combined.has(k)) combined.set(k, puzzle)
    }
  }

  return [...combined.values()]
}
